In [3]:
import pandas as pd

In [4]:
data=pd.read_csv('prep.csv')

In [5]:
data

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [6]:
df=pd.get_dummies(data,drop_first=True)

In [7]:
indep_X=df.drop('classification_yes',axis=1)

In [8]:
indep_X

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,True,False,False,False,False,False,False,True,True,False
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,True,False,False,False,False,False,True,False,False
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,True,False,False,False,False,False,True,False,False
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,True,False,False,False,False,False,True,False,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,True,False,False,False,False,False,True,False,False
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,True,False,False,True,True,False,True,False,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,True,False,False,True,True,False,False,False,False
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,True,False,False,True,True,False,True,False,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,True,False,False,False,False,False,True,False,False

In [9]:
dep_Y=df['classification_yes']

In [10]:
dep_Y

0       True
1       True
2       True
3       True
4       True
       ...
394     True
395     True
396     True
397     True
398    False
Name: classification_yes, Length: 399, dtype: bool

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [25]:
def split_stdScallar(indep_X,dep_Y):
    X_train,X_test,Y_train,Y_test=train_test_split(indep_X,dep_Y,test_size=0.25,random_state=0)
    sc=StandardScaler()
    X_train=sc.fit_transform(X_train,Y_train)
    X_test=sc.transform(X_test)
    return X_train,X_test,Y_train,Y_test

In [26]:
from sklearn.metrics import r2_score

In [27]:
def r2_score_measure(regressor,X_test,Y_test):
    Y_pred=regressor.predict(X_test)
    r2=r2_score(Y_test,Y_pred)
    return r2

In [28]:
from sklearn.linear_model import LinearRegression
def Linear_regression(X_train,Y_train,X_test,Y_test):
    regressor=LinearRegression()
    regressor.fit(X_train,Y_train)
    Y_pred=regressor.predict(X_test)
    r2=r2_score(Y_test,Y_pred)
    return r2

In [29]:
from sklearn.svm import SVR
def svm_linear(X_train,Y_train,X_test,Y_test):
    regressor=SVR(kernel='linear')
    regressor.fit(X_train,Y_train)
    Y_pred=regressor.predict(X_test)
    r2=r2_score(Y_test,Y_pred)
    return r2

In [30]:
from sklearn.svm import SVR
def svm_nonlinear(X_train,Y_train,X_test,Y_test):
    regressor=SVR(kernel='rbf')
    regressor.fit(X_train,Y_train)
    Y_pred=regressor.predict(X_test)
    r2=r2_score(Y_test,Y_pred)
    return r2

In [31]:
from sklearn.tree import DecisionTreeRegressor
def decission(X_train,Y_train,X_test,Y_test):
    regressor=DecisionTreeRegressor(random_state=0)
    regressor.fit(X_train,Y_train)
    Y_pred=regressor.predict(X_test)
    r2=r2_score(Y_test,Y_pred)
    return r2

In [32]:
from sklearn.ensemble import RandomForestRegressor
def random(X_train,Y_train,X_test,Y_test):
    regressor=RandomForestRegressor(n_estimators = 10, random_state = 0)
    regressor.fit(X_train,Y_train)
    Y_pred=regressor.predict(X_test)
    r2=r2_score(Y_test,Y_pred)
    return r2

In [33]:
from sklearn.feature_selection import RFE
def ref_feature(indep_X,dep_Y,n):
    rfe_results = []
    models = [
        LinearRegression(),
        SVR(kernel='linear'),
        DecisionTreeRegressor(random_state=0),
        RandomForestRegressor(n_estimators=10, random_state=0)
    ]
    for model in models:
        rfe=RFE(estimator=model,n_features_to_select=n)
        selected_features=rfe.fit_transform(indep_X,dep_Y)
        rfe_results.append(selected_features)
    return rfe_results

In [34]:
def rfe_regression(acclog,accsvml,accdes,accrf): 
    
    rfedataframe=pd.DataFrame(index=['Linear','SVC','Random','DecisionTree'],columns=['Linear','SVMl',
                                                                                        'Decision','Random'])

    for number,idex in enumerate(rfedataframe.index):
        
        rfedataframe['Linear'][idex]=acclog[number]       
        rfedataframe['SVMl'][idex]=accsvml[number]
        rfedataframe['Decision'][idex]=accdes[number]
        rfedataframe['Random'][idex]=accrf[number]
    return rfedataframe

In [35]:
rfelist=ref_feature(indep_X,dep_Y,3)

In [37]:
rfelist

[array([[1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 0.],
        ...,
        [1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], shape=(399, 3)),
 array([[1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 0.],
        ...,
        [1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], shape=(399, 3)),
 array([[12.51815562,  1.        ,  0.        ],
        [10.7       ,  1.        ,  0.        ],
        [12.        ,  0.        ,  0.        ],
        ...,
        [ 9.1       ,  1.        ,  0.        ],
        [ 8.5       ,  0.        ,  0.        ],
        [16.3       ,  0.        ,  0.        ]], shape=(399, 3)),
 array([[ 3.        , 12.51815562,  0.        ],
        [ 2.        , 10.7       ,  0.        ],
        [ 1.        , 12.        ,  0.        ],
        ...,
        [ 3.        ,  9.1       ,  0.        ],
        [ 0.        ,  8.5       ,  0.        ],
        [ 0.        , 16.3       ,  0.        ]], shape=(399, 3))]

In [38]:
acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

In [39]:
for i in rfelist:   
    X_train, X_test, Y_train, Y_test=split_stdScallar(i,dep_Y)  
    r2_lin=Linear_regression(X_train,Y_train,X_test,Y_test)
    acclin.append(r2_lin)
    
    r2_sl=svm_linear(X_train,Y_train,X_test,Y_test)    
    accsvml.append(r2_sl)
    
    r2_NL=svm_nonlinear(X_train,Y_train,X_test,Y_test)
    accsvmnl.append(r2_NL)
    
    r2_d=decission(X_train,Y_train,X_test,Y_test)
    accdes.append(r2_d)
    
    r2_r=random(X_train,Y_train,X_test,Y_test)
    accrf.append(r2_r)
    
    
result=rfe_regression(acclin,accsvml,accdes,accrf)

C:\Users\mojayara\AppData\Local\Temp\ipykernel_9640\1005540822.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['Linear'][idex]=acclog[number]
C:\Users\mojayara\AppData\Local\Temp\ipykernel_9640\1005540822.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['SVMl'][idex]=accsvml[number]
C:\Users\mojayara\AppData\Local\Temp\ipykernel_9640\1005540822.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['Decision'][idex]=accdes[number]
C:\Users\mojayara\AppData\Local\Temp\ipykernel_9640\1005540822.py:11: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['Random'][idex]=accrf[number]

In [40]:
result

                Linear      SVMl  Decision    Random
Linear        0.441961  0.262153  0.441961  0.441816
SVC           0.441961  0.262153  0.441961  0.441816
Random        0.664893  0.609652  0.965961  0.916304
DecisionTree  0.676174  0.670691  0.933504  0.887256